#markdown: rdiscount
markdown: redcarpet
timezone: Europe/Kiev
pygments: true
permalink: /posts/:title
#rdiscount:
#  extensions: [smart]
title : realf
production_url : http://realf.github.io
description: "Codes, projects and other things by realf."
disqus_shortname: realf
#analytics: UA-32899481-1
#gauges: 50f2b533613f5d7c8000000c
author :
  name : realf
  github : realf
  twitter : realfDev
  email: dunets.devel@gmail.com
